### ISSUE TITLE
Todo collection

### ISSUE THREAD

**Issue by krauthex** [somexlab/fastddm#101]
**Description**
A non-ordered list of ToDos that will receive their own issues in time.

**ToDos**
- [x] add `chunkify` function to `utils`
- [x] #106
- [x] #105
- [x] #116
- [ ] data storage: it will probably make sense to store the data with single precision, regardless of the compute precision, but this will require rethinking the whole package so it is left for the future
- [ ] GUI - structurator: add `chunkify` to the structurator tab
- [ ] GUI - structurator: some of the elements in the table are seldom used; we may want to tick them from a dedicated menu to make them visible in the table or build an area below the table with the different parameters to set (the table would then just show the file name, the tick and some minimal read-only information). We may need to find a way to name the output files depending on the operations performed on the videos (windowing, time-dependent analysis using chunkify, etc)
- [ ] GUI - fix video player: the matplotlib area in the widget does not resize with the window; moreover, it would be nice to have the buttons in the matplotlib navigation toolbar, plus a text edit area next to the horizontal slider
- [ ] GUI - video player: as an additional feature, we may want to display/hide (via a dedicated push button) the window function (if selected)
- [ ] GUI - image structure function player: we need to show the image structure function in an efficient way (see the pims framework for storing/reading binary files) and the azimuthal average sector/weights/bins etc
- [ ] GUI - fit tab: the fit tab should obey the rule _one dataset - one model_, meaning no batch mode should be offered. It would be mainly used to fit datasets present in a single folder (so, ideally, from a single experiment/project) individually, with the only advantage of having them accessible from the same place without the need to open them every time (the data will be loaded when needed). 
- [ ] GUI - fit tab: as a second step, we may want to improve the visualization tool in order to display functions from different datasets on the same plot (e.g., sector averages from same image structure function, particles with different size, etc)
- [ ] GUI - fit tab: lmfit also gives the possibility to save models. We may want to allow users to build their own set of fit functions
- [ ] GUI - particle sizer: the particle sizer would in principle add the possibility to either collapse the data scaling by $q^2$ the time axis or to fit the functions with different models (exponential, cumulants mainly) and then the characteristic relaxation time. In both cases, the user must have the possibility to select the range of q where the fit should be done (with a double slider in a visualizer)
- [ ] GUI - contin: the contin tab (which in principle addresses the same issue of the particle sizer) should be kept separate from the particle sizer tab. We also need to include the python contin-like project already present on the web
